version: '3'

services:
  mysql:
    image: mysql:5.7
    volumes:
      - 'mysql_data:/bitnami'
    ports:
      - '4306:3306'
    environment:
      MYSQL_DATABASE: bitnami_wordpress
      MYSQL_USER: bn_wordpress
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      # ALLOW_EMPTY_PASSWORD: 'yes'
  wordpress:
    image: 'bitnami/wordpress:latest'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'wordpress_data:/bitnami'
      - ${WORDPRESS_THEME_LOCAL_PATH}:/bitnami/wordpress/wp-content/themes/${WORDPRESS_THEME_NAME}
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT_NUMBER: 3306
      # WORDPRESS_DATABASE_USER: bn_wordpress
      WORDPRESS_DATABASE_USER: root
      WORDPRESS_DATABASE_PASSWORD: password
      WORDPRESS_DATABASE_NAME: bitnami_wordpress
      # ALLOW_EMPTY_PASSWORD: 'yes'
volumes:
  mysql_data:
    driver: local
  wordpress_data:
    driver: local
